apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi
  ports:
    - protocol: TCP
      port: 80  # Puerto accesible desde fuera del clúster
      targetPort: 8000  # Puerto en el contenedor de FastAPI
  type: NodePort

